import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/globals.css";
import { FramerMotionNavBar } from "@/components/framer_motion/animated_nav";
import ThemeContextProvider from "@/contexts/theme_ctx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-[120vh] flex flex-col`}
      >
        {/* <ThemeContextProvider> */}
        <FramerMotionNavBar />
        {children}
        {/* </ThemeContextProvider> */}
      </body>
    </html>
  );
}
